name: Imfit CI

on:
  push:
#      branches: [ main ]
#  pull_request:
#      branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      
      # Steps are the individual actions for each job
      steps:
        # Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install Python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install numpy astropy

        
        # Run a set of commands using the shell
        - name: setup
          run: |
            sudo apt-get update -qq
            sudo apt-get install -y scons
            sudo apt-get install -y libfftw3-dev
            sudo apt-get install -y libcfitsio-dev
            sudo apt-get install -y libgsl-dev
            sudo apt-get install -y libnlopt-dev
            sudo apt-get install -y cxxtest
      
        - name: unit tests
          run: ./run_unit_tests.sh
      
        - name: build executables
          run: |
            scons makeimage
            scons imfit
            scons imfit-mcmc
        
        - name: regression tests
          run: ./do_makeimage_tests
      
